name = "acearchive-submission"
main = "src/index.ts"
compatibility_date = "2023-09-22"

[[d1_databases]]
binding = "DB"
database_name = "acearchive-artifacts"
database_id = "77cf050e-a0f7-4571-b94e-1e8f593cf4ae"
