name = "acearchive-submission"
main = "src/index.ts"
compatibility_date = "2023-09-22"

[env.prod]

  [env.prod.route]
  pattern = "submit.acearchive.lgbt"
  custom_domain = true

  [[env.prod.d1_databases]]
  binding = "DB"
  database_name = "acearchive-artifacts"
  database_id = "ffd316de-0455-429b-90c7-45f935183333"

[env.dev]

  [env.dev.route]
  pattern = "submit-dev.acearchive.lgbt"
  custom_domain = true

  [[env.dev.d1_databases]]
  binding = "DB"
  database_name = "acearchive-artifacts-dev"
  database_id = "078c47dc-e6ae-4edf-89b3-db5a6bb1b4d6"
