name = "acearchive-submission"
main = "src/index.ts"
compatibility_date = "2023-09-22"

[route]
pattern = "submit.acearchive.lgbt"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "acearchive-artifacts"
database_id = "ffd316de-0455-429b-90c7-45f935183333"
preview_database_id = "689894b6-d786-4247-bd64-b3071fd2d609"

[env.dev]

  [env.dev.route]
  pattern = "submit-dev.acearchive.lgbt"
  custom_domain = true

  [[env.dev.d1_databases]]
  binding = "DB"
  database_name = "acearchive-artifacts-dev"
  database_id = "689894b6-d786-4247-bd64-b3071fd2d609"
